=== AmpScm/AnkhSVN/branches/newauth/doc/uml/UseCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Jim Arlow (Mountain Way Limited) -->
<xs:schema xmlns="http://tempuri.org/UseCase.xsd" targetNamespace="http://tempuri.org/UseCase.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="UseCase">
		<xs:annotation>
			<xs:documentation>The use case schema</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Preface">
					<xs:annotation>
						<xs:documentation>This section contains the preamble to the use case.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string">
								<xs:annotation>
									<xs:documentation>The use case name.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="ID" type="UseCaseIDType">
								<xs:annotation>
									<xs:documentation>The use case identifier.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Actors">
								<xs:annotation>
									<xs:documentation>A list of the actors involved in the use case.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ActorID" type="ActorIDType" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>The identifier for an actor.</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Summary" type="xs:string">
								<xs:annotation>
									<xs:documentation>A brief summary of the use case semantics.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Relationships" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Include, extend or generalization realtionships that the use case is involved in.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Relationship" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>An include, extend or generalization relationship and it's target use case ID.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="include"/>
															<xs:enumeration value="extend"/>
															<xs:enumeration value="generalization"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="useCaseID" type="UseCaseIDType" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="MainFlow" type="FlowType">
					<xs:annotation>
						<xs:documentation>The main flow.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="AlternativeFlow" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Alternative flows.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="FlowType">
								<xs:attribute name="name" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="FlowType">
		<xs:sequence>
			<xs:element name="Preconditions" minOccurs="0">
				<xs:annotation>
					<xs:documentation>A list of preconditions.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Precondition" type="xs:string" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>A precondition that must be true before the use case can execute.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="FlowElements">
				<xs:annotation>
					<xs:documentation>A list of flow elements.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="FlowElement" type="FlowElementType" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>An element of the use case flow.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Postconditions" minOccurs="0">
				<xs:annotation>
					<xs:documentation>A list of postconditions.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Postcondition" type="xs:string" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>A postcondition that will be true after the use case has ececuted.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RelationshipType">
		<xs:sequence>
			<xs:element name="UseCaseID" type="UseCaseIDType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="include"/>
					<xs:enumeration value="extend"/>
					<xs:enumeration value="generalization"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ActorIDType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="FlowElementType">
		<xs:choice>
			<xs:element name="Step">
				<xs:annotation>
					<xs:documentation>A step in the use case.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="If">
				<xs:annotation>
					<xs:documentation>A branch.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="IfElement" type="FlowElementType" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>An element in the If statement.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="condition" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="While">
				<xs:annotation>
					<xs:documentation>A loop.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="WhileElement" type="FlowElementType" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>An element in the loop.</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="condition" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Include">
				<xs:annotation>
					<xs:documentation>An include.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="useCaseID" type="UseCaseIDType" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ExtensionPoint">
				<xs:annotation>
					<xs:documentation>An extension point.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="UseCaseIDType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
</xs:schema>

=== AmpScm/AnkhSVN/trunk/doc/uml/CreateNewCustomerUC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Jim Arlow (Mountain Way Limited) -->
<?xml-stylesheet type="text/xsl" href="D:\cvt\Protected\Business Archetype Book\UseCaseSchema2\UseCaseXSL1.xsl"?>
<UseCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\cvt\Protected\Business Archetype Book\UseCaseSchema2\UseCase.xsd">
	<Preface>
		<Name>CreateNewCustomer</Name>
		<ID>UC2</ID>
		<Actors>
			<ActorID>Customer</ActorID>
		</Actors>
		<Summary>Create a new customer record.</Summary>
	</Preface>
	<MainFlow>
		<Preconditions>
			<Precondition>The Customer is not logged on to the system</Precondition>
		</Preconditions>
		<FlowElements>
			<FlowElement>
				<Step>The use case begins when the Customer selects "New Customer".</Step>
			</FlowElement>
			<FlowElement>
				<Step>The system asks the Customer to enter a user name and password.</Step>
			</FlowElement>
			<FlowElement>
				<Step>The Customer enters the requested information.</Step>
			</FlowElement>
			<FlowElement>
				<Step>The system checks to see if the user name is available and the password is valid.</Step>
			</FlowElement>
			<FlowElement>
				<While condition="the username is not available or the password is invalid">
					<WhileElement>
						<Step>The system asks for a new user name and/or password.</Step>
					</WhileElement>
					<WhileElement>
						<While condition="Test">
							<WhileElement>
								<Step>The system asks for a new user name and/or password.</Step>
							</WhileElement>
						</While>
					</WhileElement>
				</While>
			</FlowElement>
			<FlowElement>
				<Step>The system asks the Customer for the following information: name and address (mandatory), shipping address (optional), email address (mandatory), phone number (optional), fax number (optional), credit card details (mandatory)</Step>
			</FlowElement>
			<FlowElement>
				<Step>The Customer enters the requested information.</Step>
			</FlowElement>
			<FlowElement>
				<While condition="mandatory information is missing">
					<WhileElement>
						<Step>The sytem asks the Customer for the missing information.</Step>
					</WhileElement>
					<WhileElement>
						<Step>The Customer enters the missing information.</Step>
					</WhileElement>
				</While>
			</FlowElement>
			<FlowElement>
				<Step>The system confirms that the customer information has been accepted.</Step>
			</FlowElement>
			<FlowElement>
				<Step>The system assigns a unique customer identifier to the customer.</Step>
			</FlowElement>
		</FlowElements>
		<Postconditions>
			<Postcondition>A new customer record has been created.</Postcondition>
			<Postcondition>The Customer is assigned a user name and password.</Postcondition>
			<Postcondition>The Customer is assigned a unique identifier.</Postcondition>
		</Postconditions>
	</MainFlow>
</UseCase>
