=== AmpScm/AnkhSVN/trunk/src/AnkhSvn/Gui/Gui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:gui="http://schemas.studioturtle.net/2007/01/gui/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.studioturtle.net/2007/01/gui/" xmlns="http://schemas.studioturtle.net/2007/01/gui/">
	<xs:complexType name="Imports-Type">
		<xs:complexContent>
			<xs:extension base="gui:Base-Type">
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" ref="gui:Import" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Group-Base">
		<xs:complexContent>
			<xs:extension base="gui:Base-Type">
				<xs:sequence>
					<xs:choice maxOccurs="unbounded" minOccurs="0">
						<xs:element ref="gui:Menu" />
						<xs:element ref="gui:MenuRef" />
						<xs:element ref="gui:Button" />
						<xs:element ref="gui:ComboBox" />
						<xs:element ref="gui:ButtonRef" />
					</xs:choice>
				</xs:sequence>
				<xs:attribute name="id" type="gui:qId" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Menu-Base">
		<xs:complexContent>
			<xs:extension base="gui:Base-Type">
				<xs:sequence>
					<xs:choice maxOccurs="unbounded" minOccurs="0">
						<xs:element ref="gui:Group" />
						<xs:element ref="gui:GroupRef" />
					</xs:choice>
				</xs:sequence>
				<xs:attribute name="id" type="gui:qId" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="qId">
		<xs:restriction base="xs:string">
			<xs:pattern value="[_a-zA-Z][a-zA-Z0-9_]*(:[a-zA-Z][a-zA-Z0-9_]*)?" />
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Base-Type" abstract="true">
		<xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="VsGui">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence>
					<xs:element ref="gui:Imports" minOccurs="0" maxOccurs="1" />
					<xs:element ref="gui:Defines" minOccurs="0" />
					<xs:element ref="gui:UI" minOccurs="0" maxOccurs="1" />
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Imports" type="gui:Imports-Type">
	</xs:element>
	<xs:element name="UI">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="gui:Base-Type">
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="gui:GroupRef" />
							<xs:element ref="gui:MenuRef" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="packageId" type="gui:qPrefix" use="required" />
					<xs:attribute name="autoBmpId" type="gui:qPrefix" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Menu">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="gui:Menu-Base">
					<xs:sequence>
					</xs:sequence>
					<xs:attribute name="priority" type="gui:intValue" use="required" />
					<xs:attribute name="value" type="gui:intValue" />
					<xs:attribute name="type" type="gui:menuType" use="optional" />
					<xs:attributeGroup ref="gui:menuFlags" />
					<xs:attribute name="name" type="xs:string" use="required" />
					<xs:attribute name="text" type="xs:string" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="MenuRef">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="gui:Menu-Base">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Group">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="gui:Group-Base">
					<xs:sequence>
					</xs:sequence>
					<xs:attribute name="priority" type="gui:intValue" use="required" />
					<xs:attribute name="value" type="gui:intValue" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="GroupRef">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="gui:Group-Base">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Import">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
			<xs:attribute name="include" type="xs:string" />
			<xs:attribute name="prefix" type="xs:string" />
			<xs:attribute name="type" type="xs:string" />
			<xs:attribute name="from" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="intValue">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value="(0x[0-9A-Fa-f]+)|([0-9]+)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="menuType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="" />
			<xs:enumeration value="Toolbar" />
			<xs:enumeration value="ToolWindowToolbar" />
			<xs:enumeration value="Context" />
			<xs:enumeration value="MenuController" />
			<xs:enumeration value="MenuControllerLatched" />
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="menuFlags">
		<xs:attribute name="alwaysCreate" type="gui:trueFalse" />
		<xs:attribute name="defaultDocked" type="gui:trueFalse" />
		<xs:attribute name="defaultInvisible" type="gui:trueFalse" />
		<xs:attribute name="dontCache" type="gui:trueFalse" />
		<xs:attribute name="dynamicVisibility" type="gui:trueFalse" />
		<xs:attribute name="noCustomize" type="gui:trueFalse" />
		<xs:attribute name="notInTBList" type="gui:trueFalse" />
		<xs:attribute name="noToolBarClose" type="gui:trueFalse" />
		<xs:attribute name="textChanges" type="gui:trueFalse" />
		<xs:attribute name="textIsAnchorCommand" type="gui:trueFalse" />
		<xs:attribute name="iconAndText" type="gui:trueFalse" />
	</xs:attributeGroup>
	<xs:simpleType name="trueFalse">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true" />
			<xs:enumeration value="false" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Button">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
			<xs:attributeGroup ref="buttonFlags" />
			<xs:attribute name="localizedName" type="xs:string" />
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="commandWellText" type="xs:string" />
			<xs:attribute name="toolTip" type="xs:string" />
			<xs:attribute name="text" type="xs:string" use="required" />
			<xs:attribute name="type" type="gui:buttonType" default="Button" />
			<xs:attribute name="iconId" type="gui:qId" />
			<xs:attribute name="priority" type="gui:intValue" use="required" />
			<xs:attribute name="value" type="gui:intValue" />
			<xs:attribute name="id" type="gui:qId" use="required" />
			<xs:attribute name="menuText" type="xs:string" />
			<xs:attribute name="iconFile" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="buttonFlags">
		<xs:attribute name="noKeyCustomize" type="gui:trueFalse" />
		<xs:attribute name="noButtonCustomize" type="gui:trueFalse" />
		<xs:attribute name="noCustomize" type="gui:trueFalse" />
		<xs:attribute name="pict" type="gui:trueFalse" />
		<xs:attribute name="textOnly" type="gui:trueFalse" />
		<xs:attribute name="iconAndText" type="gui:trueFalse" />
		<xs:attribute name="textContextUseButton" type="gui:trueFalse" />
		<xs:attribute name="textMenuUseButtton" type="gui:trueFalse" />
		<xs:attribute name="textMenuCtrlUseMenu" type="gui:trueFalse" />
		<xs:attribute name="textCascadeUseButton" type="gui:trueFalse" />
		<xs:attribute name="textChanges" type="gui:trueFalse" />
		<xs:attribute name="defaultDisabled" type="gui:trueFalse" />
		<xs:attribute name="defaultInvisible" type="gui:trueFalse" />
		<xs:attribute name="dynamicVisibility" type="gui:trueFalse" />
		<xs:attribute name="dynamicItemStart" type="gui:trueFalse" />
		<xs:attribute name="commandWellOnly" type="gui:trueFalse" />
		<xs:attribute name="allowParams" type="gui:trueFalse" />
		<xs:attribute name="postExec" type="gui:trueFalse" />
		<xs:attribute name="dontCache" type="gui:trueFalse" />
		<xs:attribute name="fixMenuController" type="gui:trueFalse" />
		<xs:attribute name="noShowOnMenuController" type="gui:trueFalse" />
		<xs:attribute name="routeToDocs" type="gui:trueFalse" />
	</xs:attributeGroup>
	<xs:simpleType name="buttonType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Button" />
			<xs:enumeration value="MenuButton" />
			<xs:enumeration value="SplitDropDown" />
			<xs:enumeration value="Swatch" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="qPrefix">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value="[_a-zA-Z][a-zA-Z0-9_]*(:[a-zA-Z][a-zA-Z0-9_]*)?" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Defines">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="gui:Define" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Define">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
			<xs:attribute name="id" type="gui:qId" />
			<xs:attribute name="value" type="gui:intValue" />
			<xs:attribute name="guid" type="gui:guidValue" />
			<xs:attribute name="string" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="guidValue">
		<xs:restriction base="xs:string">
			<xs:minLength value="36" />
			<xs:maxLength value="36" />
			<xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ComboBox">
		<xs:complexType>
			<xs:sequence>
			</xs:sequence>
			<xs:attributeGroup ref="gui:comboFlags" />
			<xs:attribute name="localizedName" type="xs:string" />
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="commandWellText" type="xs:string" />
			<xs:attribute name="toolTip" type="xs:string" />
			<xs:attribute name="text" type="xs:string" use="required" />
			<xs:attribute name="type" type="gui:comboBoxType" use="required" />
			<xs:attribute name="priority" type="gui:intValue" use="required" />
			<xs:attribute name="value" type="gui:intValue" />
			<xs:attribute name="id" type="gui:qId" use="required" />
			<xs:attribute name="menuText" type="xs:string" />
			<xs:attribute name="fillCommand" type="gui:qPrefix" use="required" />
			<xs:attribute name="width" type="xs:int" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="comboFlags">
		<xs:attribute name="noKeyCustomize" type="gui:trueFalse" />
		<xs:attribute name="noButtonCustomize" type="gui:trueFalse" />
		<xs:attribute name="noCustomize" type="gui:trueFalse" />
		<xs:attribute name="defaultInvisible" type="gui:trueFalse" />
		<xs:attribute name="dynamicVisibility" type="gui:trueFalse" />
		<xs:attribute name="ommandWellOnly" type="gui:trueFalse" />
		<xs:attribute name="iconAndText" type="gui:trueFalse" />
		<xs:attribute name="filterKeys" type="gui:trueFalse" />
		<xs:attribute name="noAutoComplete" type="gui:trueFalse" />
		<xs:attribute name="caseSensitive" type="gui:trueFalse" />
		<xs:attribute name="stretchHorizontally" type="gui:trueFalse" />
	</xs:attributeGroup>
	<xs:simpleType name="comboBoxType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MRUCombo" />
			<xs:enumeration value="DynamicCombo" />
			<xs:enumeration value="DropDownCombo" />
			<xs:enumeration value="IndexCombo" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="ButtonRef">
		<xs:complexType>
			<xs:sequence />
			<xs:attribute name="priority" type="gui:intValue" use="required" />
			<xs:attribute name="id" type="gui:qId" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AmpScm/AnkhSVN/src/AnkhSvn/Gui/AnkhSvn.xml
<?xml version="1.0" encoding="utf-8" ?>
<VsGui version="1.0"  xmlns="http://schemas.studioturtle.net/2007/01/gui/" 
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	   xsi:schemaLocation="http://schemas.studioturtle.net/2007/01/gui/ Gui.xsd">
	<Imports>
		<Import include="stdidcmd.h" />
		<Import include="vsshlids.h" />
		<Import include="msobtnid.h" />
		<Import type="AnkhSvn.Ids.AnkhId" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Ankh_" />
		<Import type="AnkhSvn.Ids.AnkhCommand" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Cmd_" />
		<Import type="AnkhSvn.Ids.AnkhCommandGroup" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Grp_" />
		<Import type="AnkhSvn.Ids.AnkhCommandMenu" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Menu_" />
	</Imports>
	<Defines>
	</Defines>
	<UI packageId="Ankh_CommandSetId" autoBmpId="StBmp">
		<MenuRef id="guidSHLMainMenu:IDM_VS_MENU_FILE">
			<Group id="Grp_FileMenuScc" priority="0x0800">
				<Menu id="Menu_FileScc" priority="0x0000" name="SvnMenu" text="Sou&amp;rce Control (Ankh)">
					<Group id="Grp_FileSccMenuUpdate" priority="0x0000">
						<Button id="Cmd_FileSccMenuUpdateLatest" priority="0x0100" text="Get &amp;Latest Version of (Ankh)" />
						<Button id="Cmd_FileSccMenuUpdateSpecific" priority="0x0200" text="&amp;Get Specific Version of (Ankh)"/>
					</Group>
				</Menu>
			</Group>
		</MenuRef>
	</UI>
</VsGui>

=== AmpScm/AnkhSVN/trunk/src/AnkhSvn/Gui/AnkhSvn.xml
<?xml version="1.0" encoding="utf-8" ?>
<VsGui version="1.0"  xmlns="http://schemas.studioturtle.net/2007/01/gui/" 
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	   xsi:schemaLocation="http://schemas.studioturtle.net/2007/01/gui/ Gui.xsd">
	<Imports>
		<Import include="stdidcmd.h" />
		<Import include="vsshlids.h" />
		<Import include="msobtnid.h" />
		<Import type="AnkhSvn.Ids.AnkhId" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Ankh_" />
		<Import type="AnkhSvn.Ids.AnkhCommand" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Cmd_" />
		<Import type="AnkhSvn.Ids.AnkhCommandGroup" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Grp_" />
		<Import type="AnkhSvn.Ids.AnkhCommandMenu" from="..\..\AnkhSvn.Ids\bin\$(Configuration)\AnkhSvn.Ids.dll" prefix="Menu_" />
	</Imports>
	<Defines>
	</Defines>
	<UI packageId="Ankh_PackageGuid" autoBmpId="StBmp">
		<MenuRef id="guidSHLMainMenu:IDM_VS_MENU_FILE">
			<Group id="Grp_FileMenuScc" priority="0x0800">
				<Menu id="Menu_FileScc" priority="0x0000" name="SvnMenu" text="Sou&amp;rce Control (Ankh)">
					<Group id="Grp_FileSccMenuUpdate" priority="0x0000">
						<Button id="Cmd_FileSccMenuUpdateLatest" priority="0x0100" text="Get &amp;Latest Version of (Ankh)" />
						<Button id="Cmd_FileSccMenuUpdateSpecific" priority="0x0200" text="&amp;Get Specific Version of (Ankh)"/>
						<Button id="Cmd_AddItem" priority="0x301" text="AddItem" />
						<Button id="Cmd_AddRepositoryRoot" priority="0x301" text="AddRepositoryRoot" />
						<Button id="Cmd_AddSolutionToRepository" priority="0x301" text="AddSolutionToRepository" />
						<Button id="Cmd_AddWorkingCopyExplorerRoot" priority="0x301" text="AddWorkingCopyExplorerRoot" />
						<Button id="Cmd_Blame" priority="0x301" text="Blame" />
						<Button id="Cmd_ChangeAdminDirName" priority="0x301" text="ChangeAdminDirName" />
						<Button id="Cmd_Checkout" priority="0x301" text="Checkout" />
						<Button id="Cmd_CheckoutFolder" priority="0x301" text="CheckoutFolder" />
						<Button id="Cmd_CheckoutSolution" priority="0x301" text="CheckoutSolution" />
						<Button id="Cmd_Cleanup" priority="0x301" text="Cleanup" />
						<Button id="Cmd_CommitItem" priority="0x301" text="CommitItem" />
						<Button id="Cmd_CopyReposExplorerUrl" priority="0x301" text="CopyReposExplorerUrl" />
						<Button id="Cmd_CreatePatch" priority="0x301" text="CreatePatch" />
						<Button id="Cmd_DiffExternalLocalItem" priority="0x301" text="DiffExternalLocalItem" />
						<Button id="Cmd_DiffLocalItem" priority="0x301" text="DiffLocalItem" />
						<Button id="Cmd_EditConfigFile" priority="0x301" text="EditConfigFile" />
						<Button id="Cmd_Export" priority="0x301" text="Export"/>
						<Button id="Cmd_ExportFolder" priority="0x301" text="ExportFolder"/>
						<Button id="Cmd_Lock" priority="0x301" text="Lock"/>
						<Button id="Cmd_Log" priority="0x301" text="Log"/>
						<Button id="Cmd_MakeDirectory" priority="0x301" text="MakeDirectory"/>
						<Button id="Cmd_Refresh" priority="0x301" text="Refresh"/>
						<Button id="Cmd_RefreshRepositoryItem" priority="0x301" text="RefreshRepositoryItem"/>
						<Button id="Cmd_Relocate" priority="0x301" text="Relocate"/>
						<Button id="Cmd_RemoveRepositoryRoot" priority="0x301" text="RemoveRepositoryRoot"/>
						<Button id="Cmd_RemoveWorkingCopyExplorerRoot" priority="0x301" text="RemoveWorkingCopyExplorerRoot"/>
						<Button id="Cmd_ResolveConflict" priority="0x301" text="ResolveConflict"/>
						<Button id="Cmd_ResolveConflictExternal" priority="0x301" text="ResolveConflictExternal"/>
						<Button id="Cmd_ReverseMerge" priority="0x301" text="ReverseMerge"/>
						<Button id="Cmd_RevertItem" priority="0x301" text="RevertItem"/>
						<Button id="Cmd_SaveToFile" priority="0x301" text="SaveToFile"/>
						<Button id="Cmd_SendErrorReport" priority="0x301" text="SendErrorReport"/>
						<Button id="Cmd_ShowCommitDialog" priority="0x301" text="ShowCommitDialog"/>
						<Button id="Cmd_ShowRepositoryExplorer" priority="0x301" text="ShowRepositoryExplorer"/>
						<Button id="Cmd_ShowWorkingCopyExplorer" priority="0x301" text="ShowWorkingCopyExplorer"/>
						<Button id="Cmd_SwitchItem" priority="0x301" text="SwitchItem"/>
						<Button id="Cmd_ToggleAnkh" priority="0x301" text="ToggleAnkh"/>
						<Button id="Cmd_Unlock" priority="0x301" text="Unlock"/>
						<Button id="Cmd_UpdateItem" priority="0x301" text="UpdateItem"/>
						<Button id="Cmd_ViewInVsNet" priority="0x301" text="ViewInVsNet"/>
						<Button id="Cmd_ViewInWindows" priority="0x301" text="ViewInWindows"/>
						<Button id="Cmd_ViewRepositoryFile" priority="0x301" text="ViewRepositoryFile"/>
						<Button id="Cmd_CheckForOrphanedTreeNodes" priority="0x301" text="CheckForOrphanedTreeNodes"/>					
					</Group>
				</Menu>
			</Group>
		</MenuRef>
	</UI>
</VsGui>
